def kubernetes_namespaces_response():
    return {'api_version': 'v1',
            'items': [{'api_version': None,
                       'kind': None,
                       'metadata': {'annotations': None,
                                    'cluster_name': None,
                                    'deletion_grace_period_seconds': None,
                                    'deletion_timestamp': None,
                                    'finalizers': None,
                                    'generate_name': None,
                                    'generation': None,
                                    'labels': {'kubernetes.io/metadata.name': 'default'},
                                    'managed_fields': [{'api_version': 'v1',
                                                        'fields_type': 'FieldsV1',
                                                        'fields_v1': {'f:metadata': {'f:labels': {'.': {},
                                                                                                  'f:kubernetes.io/metadata.name': {}}}},
                                                        'manager': 'kube-apiserver',
                                                        'operation': 'Update'}],
                                    'name': 'default',
                                    'namespace': None,
                                    'owner_references': None,
                                    'resource_version': '204',
                                    'self_link': None,
                                    'uid': 'b525701d-a42a-4611-a936-258dd5a45f43'},
                       'spec': {'finalizers': ['kubernetes']},
                       'status': {'conditions': None, 'phase': 'Active'}},
                      {'api_version': None,
                       'kind': None,
                       'metadata': {'annotations': None,
                                    'cluster_name': None,
                                    'deletion_grace_period_seconds': None,
                                    'deletion_timestamp': None,
                                    'finalizers': None,
                                    'generate_name': None,
                                    'generation': None,
                                    'labels': {'kubernetes.io/metadata.name': 'kube-node-lease'},
                                    'managed_fields': [{'api_version': 'v1',
                                                        'fields_type': 'FieldsV1',
                                                        'fields_v1': {'f:metadata': {'f:labels': {'.': {},
                                                                                                  'f:kubernetes.io/metadata.name': {}}}},
                                                        'manager': 'kube-apiserver',
                                                        'operation': 'Update'}],
                                    'name': 'kube-node-lease',
                                    'namespace': None,
                                    'owner_references': None,
                                    'resource_version': '43',
                                    'self_link': None,
                                    'uid': '5585d833-241d-4dab-92d0-7e094dcb2378'},
                       'spec': {'finalizers': ['kubernetes']},
                       'status': {'conditions': None, 'phase': 'Active'}},
                      {'api_version': None,
                       'kind': None,
                       'metadata': {'annotations': None,
                                    'cluster_name': None,
                                    'deletion_grace_period_seconds': None,
                                    'deletion_timestamp': None,
                                    'finalizers': None,
                                    'generate_name': None,
                                    'generation': None,
                                    'labels': {'kubernetes.io/metadata.name': 'kube-public'},
                                    'managed_fields': [{'api_version': 'v1',
                                                        'fields_type': 'FieldsV1',
                                                        'fields_v1': {'f:metadata': {'f:labels': {'.': {},
                                                                                                  'f:kubernetes.io/metadata.name': {}}}},
                                                        'manager': 'kube-apiserver',
                                                        'operation': 'Update'}],
                                    'name': 'kube-public',
                                    'namespace': None,
                                    'owner_references': None,
                                    'resource_version': '29',
                                    'self_link': None,
                                    'uid': 'ee81fc36-4be9-443f-8b5d-e6be9b0db3f5'},
                       'spec': {'finalizers': ['kubernetes']},
                       'status': {'conditions': None, 'phase': 'Active'}},
                      {'api_version': None,
                       'kind': None,
                       'metadata': {'annotations': None,
                                    'cluster_name': None,
                                    'deletion_grace_period_seconds': None,
                                    'deletion_timestamp': None,
                                    'finalizers': None,
                                    'generate_name': None,
                                    'generation': None,
                                    'labels': {'kubernetes.io/metadata.name': 'kube-system'},
                                    'managed_fields': [{'api_version': 'v1',
                                                        'fields_type': 'FieldsV1',
                                                        'fields_v1': {'f:metadata': {'f:labels': {'.': {},
                                                                                                  'f:kubernetes.io/metadata.name': {}}}},
                                                        'manager': 'kube-apiserver',
                                                        'operation': 'Update'}],
                                    'name': 'kube-system',
                                    'namespace': None,
                                    'owner_references': None,
                                    'resource_version': '13',
                                    'self_link': None,
                                    'uid': 'f55941c3-93b7-47e4-b917-cdaa2b757248'},
                       'spec': {'finalizers': ['kubernetes']},
                       'status': {'conditions': None, 'phase': 'Active'}}],
            'kind': 'NamespaceList',
            'metadata': {'_continue': None,
                         'remaining_item_count': None,
                         'resource_version': '470',
                         'self_link': None}}


def kubernetes_pods_response():
    return {'api_version': 'v1',
            'items': [{'api_version': None,
                       'kind': None,
                       'metadata': {'annotations': None,
                                    'cluster_name': None,
                                    'deletion_grace_period_seconds': None,
                                    'deletion_timestamp': None,
                                    'finalizers': None,
                                    'generate_name': 'coredns-78fcd69978-',
                                    'generation': None,
                                    'labels': {'k8s-app': 'kube-dns',
                                               'pod-template-hash': '78fcd69978'},
                                    'managed_fields': [{'api_version': 'v1',
                                                        'fields_type': 'FieldsV1',
                                                        'fields_v1': {'f:metadata': {'f:generateName': {},
                                                                                     'f:labels': {'.': {},
                                                                                                  'f:k8s-app': {},
                                                                                                  'f:pod-template-hash': {}},
                                                                                     'f:ownerReferences': {'.': {},
                                                                                                           'k:{"uid":"232837b4-dc80-4785-b145-fbdb8f5dd2f3"}': {}}},
                                                                      'f:spec': {'f:containers': {
                                                                          'k:{"name":"coredns"}': {'.': {},
                                                                                                   'f:args': {},
                                                                                                   'f:image': {},
                                                                                                   'f:imagePullPolicy': {},
                                                                                                   'f:livenessProbe': {
                                                                                                       '.': {},
                                                                                                       'f:failureThreshold': {},
                                                                                                       'f:httpGet': {
                                                                                                           '.': {},
                                                                                                           'f:path': {},
                                                                                                           'f:port': {},
                                                                                                           'f:scheme': {}},
                                                                                                       'f:initialDelaySeconds': {},
                                                                                                       'f:periodSeconds': {},
                                                                                                       'f:successThreshold': {},
                                                                                                       'f:timeoutSeconds': {}},
                                                                                                   'f:name': {},
                                                                                                   'f:ports': {'.': {},
                                                                                                               'k:{"containerPort":53,"protocol":"TCP"}': {
                                                                                                                   '.': {},
                                                                                                                   'f:containerPort': {},
                                                                                                                   'f:name': {},
                                                                                                                   'f:protocol': {}},
                                                                                                               'k:{"containerPort":53,"protocol":"UDP"}': {
                                                                                                                   '.': {},
                                                                                                                   'f:containerPort': {},
                                                                                                                   'f:name': {},
                                                                                                                   'f:protocol': {}},
                                                                                                               'k:{"containerPort":9153,"protocol":"TCP"}': {
                                                                                                                   '.': {},
                                                                                                                   'f:containerPort': {},
                                                                                                                   'f:name': {},
                                                                                                                   'f:protocol': {}}},
                                                                                                   'f:readinessProbe': {
                                                                                                       '.': {},
                                                                                                       'f:failureThreshold': {},
                                                                                                       'f:httpGet': {
                                                                                                           '.': {},
                                                                                                           'f:path': {},
                                                                                                           'f:port': {},
                                                                                                           'f:scheme': {}},
                                                                                                       'f:periodSeconds': {},
                                                                                                       'f:successThreshold': {},
                                                                                                       'f:timeoutSeconds': {}},
                                                                                                   'f:resources': {
                                                                                                       '.': {},
                                                                                                       'f:limits': {
                                                                                                           '.': {},
                                                                                                           'f:memory': {}},
                                                                                                       'f:requests': {
                                                                                                           '.': {},
                                                                                                           'f:cpu': {},
                                                                                                           'f:memory': {}}},
                                                                                                   'f:securityContext': {
                                                                                                       '.': {},
                                                                                                       'f:allowPrivilegeEscalation': {},
                                                                                                       'f:capabilities': {
                                                                                                           '.': {},
                                                                                                           'f:add': {},
                                                                                                           'f:drop': {}},
                                                                                                       'f:readOnlyRootFilesystem': {}},
                                                                                                   'f:terminationMessagePath': {},
                                                                                                   'f:terminationMessagePolicy': {},
                                                                                                   'f:volumeMounts': {
                                                                                                       '.': {},
                                                                                                       'k:{"mountPath":"/etc/coredns"}': {
                                                                                                           '.': {},
                                                                                                           'f:mountPath': {},
                                                                                                           'f:name': {},
                                                                                                           'f:readOnly': {}}}}},
                                                                                 'f:dnsPolicy': {},
                                                                                 'f:enableServiceLinks': {},
                                                                                 'f:nodeSelector': {},
                                                                                 'f:priorityClassName': {},
                                                                                 'f:restartPolicy': {},
                                                                                 'f:schedulerName': {},
                                                                                 'f:securityContext': {},
                                                                                 'f:serviceAccount': {},
                                                                                 'f:serviceAccountName': {},
                                                                                 'f:terminationGracePeriodSeconds': {},
                                                                                 'f:tolerations': {},
                                                                                 'f:volumes': {'.': {},
                                                                                               'k:{"name":"config-volume"}': {
                                                                                                   '.': {},
                                                                                                   'f:configMap': {
                                                                                                       '.': {},
                                                                                                       'f:defaultMode': {},
                                                                                                       'f:items': {},
                                                                                                       'f:name': {}},
                                                                                                   'f:name': {}}}}},
                                                        'manager': 'kube-controller-manager',
                                                        'operation': 'Update'}],
                                    'name': 'mm-demo',
                                    'namespace': 'kube-system',
                                    'owner_references': [{'api_version': 'apps/v1',
                                                          'block_owner_deletion': True,
                                                          'controller': True,
                                                          'kind': 'ReplicaSet',
                                                          'name': 'coredns-78fcd69978',
                                                          'uid': '232837b4-dc80-4785-b145-fbdb8f5dd2f3'}],
                                    'resource_version': '4201',
                                    'self_link': None,
                                    'uid': '1036dd74-0ea9-46ad-bfa4-d68acc8a6dda'},
                       'spec': {'active_deadline_seconds': None,
                                'affinity': None,
                                'automount_service_account_token': None,
                                'containers': [{'args': ['-conf', '/etc/coredns/Corefile'],
                                                'command': None,
                                                'env': None,
                                                'env_from': None,
                                                'image': 'k8s.gcr.io/coredns/coredns:v1.8.4',
                                                'image_pull_policy': 'IfNotPresent',
                                                'lifecycle': None,
                                                'liveness_probe': {'_exec': None,
                                                                   'failure_threshold': 5,
                                                                   'http_get': {'host': None,
                                                                                'http_headers': None,
                                                                                'path': '/health',
                                                                                'port': 8080,
                                                                                'scheme': 'HTTP'},
                                                                   'initial_delay_seconds': 60,
                                                                   'period_seconds': 10,
                                                                   'success_threshold': 1,
                                                                   'tcp_socket': None,
                                                                   'timeout_seconds': 5},
                                                'name': 'coredns',
                                                'ports': [{'container_port': 53,
                                                           'host_ip': None,
                                                           'host_port': None,
                                                           'name': 'dns',
                                                           'protocol': 'UDP'},
                                                          {'container_port': 53,
                                                           'host_ip': None,
                                                           'host_port': None,
                                                           'name': 'dns-tcp',
                                                           'protocol': 'TCP'},
                                                          {'container_port': 9153,
                                                           'host_ip': None,
                                                           'host_port': None,
                                                           'name': 'metrics',
                                                           'protocol': 'TCP'}],
                                                'readiness_probe': {'_exec': None,
                                                                    'failure_threshold': 3,
                                                                    'http_get': {'host': None,
                                                                                 'http_headers': None,
                                                                                 'path': '/ready',
                                                                                 'port': 8181,
                                                                                 'scheme': 'HTTP'},
                                                                    'initial_delay_seconds': None,
                                                                    'period_seconds': 10,
                                                                    'success_threshold': 1,
                                                                    'tcp_socket': None,
                                                                    'timeout_seconds': 1},
                                                'resources': {'limits': {'memory': '170Mi'},
                                                              'requests': {'cpu': '100m',
                                                                           'memory': '70Mi'}},
                                                'security_context': {'allow_privilege_escalation': False,
                                                                     'capabilities': {'add': ['NET_BIND_SERVICE'],
                                                                                      'drop': ['all']},
                                                                     'privileged': None,
                                                                     'proc_mount': None,
                                                                     'read_only_root_filesystem': True,
                                                                     'run_as_group': None,
                                                                     'run_as_non_root': None,
                                                                     'run_as_user': None,
                                                                     'se_linux_options': None,
                                                                     'seccomp_profile': None,
                                                                     'windows_options': None},
                                                'startup_probe': None,
                                                'stdin': None,
                                                'stdin_once': None,
                                                'termination_message_path': '/dev/termination-log',
                                                'termination_message_policy': 'File',
                                                'tty': None,
                                                'volume_devices': None,
                                                'volume_mounts': [{'mount_path': '/etc/coredns',
                                                                   'mount_propagation': None,
                                                                   'name': 'config-volume',
                                                                   'read_only': True,
                                                                   'sub_path': None,
                                                                   'sub_path_expr': None},
                                                                  {
                                                                      'mount_path': '/var/run/secrets/kubernetes.io/serviceaccount',
                                                                      'mount_propagation': None,
                                                                      'name': 'kube-api-access-4dp5z',
                                                                      'read_only': True,
                                                                      'sub_path': None,
                                                                      'sub_path_expr': None}],
                                                'working_dir': None}],
                                'dns_config': None,
                                'dns_policy': 'Default',
                                'enable_service_links': True,
                                'ephemeral_containers': None,
                                'host_aliases': None,
                                'host_ipc': None,
                                'host_network': None,
                                'host_pid': None,
                                'hostname': None,
                                'image_pull_secrets': None,
                                'init_containers': None,
                                'node_name': 'minikube',
                                'node_selector': {'kubernetes.io/os': 'linux'},
                                'overhead': None,
                                'preemption_policy': 'PreemptLowerPriority',
                                'priority': 2000000000,
                                'priority_class_name': 'system-cluster-critical',
                                'readiness_gates': None,
                                'restart_policy': 'Always',
                                'runtime_class_name': None,
                                'scheduler_name': 'default-scheduler',
                                'security_context': {'fs_group': None,
                                                     'fs_group_change_policy': None,
                                                     'run_as_group': None,
                                                     'run_as_non_root': None,
                                                     'run_as_user': None,
                                                     'se_linux_options': None,
                                                     'seccomp_profile': None,
                                                     'supplemental_groups': None,
                                                     'sysctls': None,
                                                     'windows_options': None},
                                'service_account': 'coredns',
                                'service_account_name': 'coredns',
                                'set_hostname_as_fqdn': None,
                                'share_process_namespace': None,
                                'subdomain': None,
                                'termination_grace_period_seconds': 30,
                                'tolerations': [{'effect': None,
                                                 'key': 'CriticalAddonsOnly',
                                                 'operator': 'Exists',
                                                 'toleration_seconds': None,
                                                 'value': None},
                                                {'effect': 'NoSchedule',
                                                 'key': 'node-role.kubernetes.io/master',
                                                 'operator': None,
                                                 'toleration_seconds': None,
                                                 'value': None},
                                                {'effect': 'NoSchedule',
                                                 'key': 'node-role.kubernetes.io/control-plane',
                                                 'operator': None,
                                                 'toleration_seconds': None,
                                                 'value': None},
                                                {'effect': 'NoExecute',
                                                 'key': 'node.kubernetes.io/not-ready',
                                                 'operator': 'Exists',
                                                 'toleration_seconds': 300,
                                                 'value': None},
                                                {'effect': 'NoExecute',
                                                 'key': 'node.kubernetes.io/unreachable',
                                                 'operator': 'Exists',
                                                 'toleration_seconds': 300,
                                                 'value': None}],
                                'topology_spread_constraints': None,
                                'volumes': [{'aws_elastic_block_store': None,
                                             'azure_disk': None,
                                             'azure_file': None,
                                             'cephfs': None,
                                             'cinder': None,
                                             'config_map': {'default_mode': 420,
                                                            'items': [{'key': 'Corefile',
                                                                       'mode': None,
                                                                       'path': 'Corefile'}],
                                                            'name': 'coredns',
                                                            'optional': None},
                                             'csi': None,
                                             'downward_api': None,
                                             'empty_dir': None,
                                             'ephemeral': None,
                                             'fc': None,
                                             'flex_volume': None,
                                             'flocker': None,
                                             'gce_persistent_disk': None,
                                             'git_repo': None,
                                             'glusterfs': None,
                                             'host_path': None,
                                             'iscsi': None,
                                             'name': 'config-volume',
                                             'nfs': None,
                                             'persistent_volume_claim': None,
                                             'photon_persistent_disk': None,
                                             'portworx_volume': None,
                                             'projected': None,
                                             'quobyte': None,
                                             'rbd': None,
                                             'scale_io': None,
                                             'secret': None,
                                             'storageos': None,
                                             'vsphere_volume': None},
                                            {'aws_elastic_block_store': None,
                                             'azure_disk': None,
                                             'azure_file': None,
                                             'cephfs': None,
                                             'cinder': None,
                                             'config_map': None,
                                             'csi': None,
                                             'downward_api': None,
                                             'empty_dir': None,
                                             'ephemeral': None,
                                             'fc': None,
                                             'flex_volume': None,
                                             'flocker': None,
                                             'gce_persistent_disk': None,
                                             'git_repo': None,
                                             'glusterfs': None,
                                             'host_path': None,
                                             'iscsi': None,
                                             'name': 'kube-api-access-4dp5z',
                                             'nfs': None,
                                             'persistent_volume_claim': None,
                                             'photon_persistent_disk': None,
                                             'portworx_volume': None,
                                             'projected': {'default_mode': 420,
                                                           'sources': [{'config_map': None,
                                                                        'downward_api': None,
                                                                        'secret': None,
                                                                        'service_account_token': {'audience': None,
                                                                                                  'expiration_seconds': 3607,
                                                                                                  'path': 'token'}},
                                                                       {'config_map': {'items': [{'key': 'ca.crt',
                                                                                                  'mode': None,
                                                                                                  'path': 'ca.crt'}],
                                                                                       'name': 'kube-root-ca.crt',
                                                                                       'optional': None},
                                                                        'downward_api': None,
                                                                        'secret': None,
                                                                        'service_account_token': None},
                                                                       {'config_map': None,
                                                                        'downward_api': {'items': [
                                                                            {'field_ref': {'api_version': 'v1',
                                                                                           'field_path': 'metadata.namespace'},
                                                                             'mode': None,
                                                                             'path': 'namespace',
                                                                             'resource_field_ref': None}]},
                                                                        'secret': None,
                                                                        'service_account_token': None}]},
                                             'quobyte': None,
                                             'rbd': None,
                                             'scale_io': None,
                                             'secret': None,
                                             'storageos': None,
                                             'vsphere_volume': None}]}},
                      {'api_version': None,
                       'kind': None,
                       'metadata': {'annotations': None,
                                    'cluster_name': None,
                                    'deletion_grace_period_seconds': None,
                                    'deletion_timestamp': None,
                                    'finalizers': None,
                                    'generate_name': 'coredns-78fcd69978-',
                                    'generation': None,
                                    'labels': {'k8s-app': 'kube-dns',
                                               'pod-template-hash': '78fcd69978'},
                                    'managed_fields': [{'api_version': 'v1',
                                                        'fields_type': 'FieldsV1',
                                                        'fields_v1': {'f:metadata': {'f:generateName': {},
                                                                                     'f:labels': {'.': {},
                                                                                                  'f:k8s-app': {},
                                                                                                  'f:pod-template-hash': {}},
                                                                                     'f:ownerReferences': {'.': {},
                                                                                                           'k:{"uid":"232837b4-dc80-4785-b145-fbdb8f5dd2f3"}': {}}},
                                                                      'f:spec': {'f:containers': {
                                                                          'k:{"name":"coredns"}': {'.': {},
                                                                                                   'f:args': {},
                                                                                                   'f:image': {},
                                                                                                   'f:imagePullPolicy': {},
                                                                                                   'f:livenessProbe': {
                                                                                                       '.': {},
                                                                                                       'f:failureThreshold': {},
                                                                                                       'f:httpGet': {
                                                                                                           '.': {},
                                                                                                           'f:path': {},
                                                                                                           'f:port': {},
                                                                                                           'f:scheme': {}},
                                                                                                       'f:initialDelaySeconds': {},
                                                                                                       'f:periodSeconds': {},
                                                                                                       'f:successThreshold': {},
                                                                                                       'f:timeoutSeconds': {}},
                                                                                                   'f:name': {},
                                                                                                   'f:ports': {'.': {},
                                                                                                               'k:{"containerPort":53,"protocol":"TCP"}': {
                                                                                                                   '.': {},
                                                                                                                   'f:containerPort': {},
                                                                                                                   'f:name': {},
                                                                                                                   'f:protocol': {}},
                                                                                                               'k:{"containerPort":53,"protocol":"UDP"}': {
                                                                                                                   '.': {},
                                                                                                                   'f:containerPort': {},
                                                                                                                   'f:name': {},
                                                                                                                   'f:protocol': {}},
                                                                                                               'k:{"containerPort":9153,"protocol":"TCP"}': {
                                                                                                                   '.': {},
                                                                                                                   'f:containerPort': {},
                                                                                                                   'f:name': {},
                                                                                                                   'f:protocol': {}}},
                                                                                                   'f:readinessProbe': {
                                                                                                       '.': {},
                                                                                                       'f:failureThreshold': {},
                                                                                                       'f:httpGet': {
                                                                                                           '.': {},
                                                                                                           'f:path': {},
                                                                                                           'f:port': {},
                                                                                                           'f:scheme': {}},
                                                                                                       'f:periodSeconds': {},
                                                                                                       'f:successThreshold': {},
                                                                                                       'f:timeoutSeconds': {}},
                                                                                                   'f:resources': {
                                                                                                       '.': {},
                                                                                                       'f:limits': {
                                                                                                           '.': {},
                                                                                                           'f:memory': {}},
                                                                                                       'f:requests': {
                                                                                                           '.': {},
                                                                                                           'f:cpu': {},
                                                                                                           'f:memory': {}}},
                                                                                                   'f:securityContext': {
                                                                                                       '.': {},
                                                                                                       'f:allowPrivilegeEscalation': {},
                                                                                                       'f:capabilities': {
                                                                                                           '.': {},
                                                                                                           'f:add': {},
                                                                                                           'f:drop': {}},
                                                                                                       'f:readOnlyRootFilesystem': {}},
                                                                                                   'f:terminationMessagePath': {},
                                                                                                   'f:terminationMessagePolicy': {},
                                                                                                   'f:volumeMounts': {
                                                                                                       '.': {},
                                                                                                       'k:{"mountPath":"/etc/coredns"}': {
                                                                                                           '.': {},
                                                                                                           'f:mountPath': {},
                                                                                                           'f:name': {},
                                                                                                           'f:readOnly': {}}}}},
                                                                          'f:dnsPolicy': {},
                                                                          'f:enableServiceLinks': {},
                                                                          'f:nodeSelector': {},
                                                                          'f:priorityClassName': {},
                                                                          'f:restartPolicy': {},
                                                                          'f:schedulerName': {},
                                                                          'f:securityContext': {},
                                                                          'f:serviceAccount': {},
                                                                          'f:serviceAccountName': {},
                                                                          'f:terminationGracePeriodSeconds': {},
                                                                          'f:tolerations': {},
                                                                          'f:volumes': {'.': {},
                                                                                        'k:{"name":"config-volume"}': {
                                                                                            '.': {},
                                                                                            'f:configMap': {
                                                                                                '.': {},
                                                                                                'f:defaultMode': {},
                                                                                                'f:items': {},
                                                                                                'f:name': {}},
                                                                                            'f:name': {}}}}},
                                                        'manager': 'kube-controller-manager',
                                                        'operation': 'Update'}],
                                    'name': 'rabbitmq-server-0',
                                    'namespace': 'kube-system',
                                    'owner_references': [{'api_version': 'apps/v1',
                                                          'block_owner_deletion': True,
                                                          'controller': True,
                                                          'kind': 'ReplicaSet',
                                                          'name': 'coredns-78fcd69978',
                                                          'uid': '232837b4-dc80-4785-b145-fbdb8f5dd2f3'}],
                                    'resource_version': '4201',
                                    'self_link': None,
                                    'uid': '1036dd74-0ea9-46ad-bfa4-d68acc8a6dda'},
                       'spec': {'active_deadline_seconds': None,
                                'affinity': None,
                                'automount_service_account_token': None,
                                'containers': [{'args': ['-conf', '/etc/coredns/Corefile'],
                                                'command': None,
                                                'env': None,
                                                'env_from': None,
                                                'image': 'k8s.gcr.io/coredns/coredns:v1.8.4',
                                                'image_pull_policy': 'IfNotPresent',
                                                'lifecycle': None,
                                                'liveness_probe': {'_exec': None,
                                                                   'failure_threshold': 5,
                                                                   'http_get': {'host': None,
                                                                                'http_headers': None,
                                                                                'path': '/health',
                                                                                'port': 8080,
                                                                                'scheme': 'HTTP'},
                                                                   'initial_delay_seconds': 60,
                                                                   'period_seconds': 10,
                                                                   'success_threshold': 1,
                                                                   'tcp_socket': None,
                                                                   'timeout_seconds': 5},
                                                'name': 'coredns',
                                                'ports': [{'container_port': 53,
                                                           'host_ip': None,
                                                           'host_port': None,
                                                           'name': 'dns',
                                                           'protocol': 'UDP'},
                                                          {'container_port': 53,
                                                           'host_ip': None,
                                                           'host_port': None,
                                                           'name': 'dns-tcp',
                                                           'protocol': 'TCP'},
                                                          {'container_port': 9153,
                                                           'host_ip': None,
                                                           'host_port': None,
                                                           'name': 'metrics',
                                                           'protocol': 'TCP'}],
                                                'readiness_probe': {'_exec': None,
                                                                    'failure_threshold': 3,
                                                                    'http_get': {'host': None,
                                                                                 'http_headers': None,
                                                                                 'path': '/ready',
                                                                                 'port': 8181,
                                                                                 'scheme': 'HTTP'},
                                                                    'initial_delay_seconds': None,
                                                                    'period_seconds': 10,
                                                                    'success_threshold': 1,
                                                                    'tcp_socket': None,
                                                                    'timeout_seconds': 1},
                                                'resources': {'limits': {'memory': '170Mi'},
                                                              'requests': {'cpu': '100m',
                                                                           'memory': '70Mi'}},
                                                'security_context': {'allow_privilege_escalation': False,
                                                                     'capabilities': {'add': ['NET_BIND_SERVICE'],
                                                                                      'drop': ['all']},
                                                                     'privileged': None,
                                                                     'proc_mount': None,
                                                                     'read_only_root_filesystem': True,
                                                                     'run_as_group': None,
                                                                     'run_as_non_root': None,
                                                                     'run_as_user': None,
                                                                     'se_linux_options': None,
                                                                     'seccomp_profile': None,
                                                                     'windows_options': None},
                                                'startup_probe': None,
                                                'stdin': None,
                                                'stdin_once': None,
                                                'termination_message_path': '/dev/termination-log',
                                                'termination_message_policy': 'File',
                                                'tty': None,
                                                'volume_devices': None,
                                                'volume_mounts': [{'mount_path': '/etc/coredns',
                                                                   'mount_propagation': None,
                                                                   'name': 'config-volume',
                                                                   'read_only': True,
                                                                   'sub_path': None,
                                                                   'sub_path_expr': None},
                                                                  {
                                                                      'mount_path': '/var/run/secrets/kubernetes.io/serviceaccount',
                                                                      'mount_propagation': None,
                                                                      'name': 'kube-api-access-4dp5z',
                                                                      'read_only': True,
                                                                      'sub_path': None,
                                                                      'sub_path_expr': None}],
                                                'working_dir': None}],
                                'dns_config': None,
                                'dns_policy': 'Default',
                                'enable_service_links': True,
                                'ephemeral_containers': None,
                                'host_aliases': None,
                                'host_ipc': None,
                                'host_network': None,
                                'host_pid': None,
                                'hostname': None,
                                'image_pull_secrets': None,
                                'init_containers': None,
                                'node_name': 'minikube',
                                'node_selector': {'kubernetes.io/os': 'linux'},
                                'overhead': None,
                                'preemption_policy': 'PreemptLowerPriority',
                                'priority': 2000000000,
                                'priority_class_name': 'system-cluster-critical',
                                'readiness_gates': None,
                                'restart_policy': 'Always',
                                'runtime_class_name': None,
                                'scheduler_name': 'default-scheduler',
                                'security_context': {'fs_group': None,
                                                     'fs_group_change_policy': None,
                                                     'run_as_group': None,
                                                     'run_as_non_root': None,
                                                     'run_as_user': None,
                                                     'se_linux_options': None,
                                                     'seccomp_profile': None,
                                                     'supplemental_groups': None,
                                                     'sysctls': None,
                                                     'windows_options': None},
                                'service_account': 'coredns',
                                'service_account_name': 'coredns',
                                'set_hostname_as_fqdn': None,
                                'share_process_namespace': None,
                                'subdomain': None,
                                'termination_grace_period_seconds': 30,
                                'tolerations': [{'effect': None,
                                                 'key': 'CriticalAddonsOnly',
                                                 'operator': 'Exists',
                                                 'toleration_seconds': None,
                                                 'value': None},
                                                {'effect': 'NoSchedule',
                                                 'key': 'node-role.kubernetes.io/master',
                                                 'operator': None,
                                                 'toleration_seconds': None,
                                                 'value': None},
                                                {'effect': 'NoSchedule',
                                                 'key': 'node-role.kubernetes.io/control-plane',
                                                 'operator': None,
                                                 'toleration_seconds': None,
                                                 'value': None},
                                                {'effect': 'NoExecute',
                                                 'key': 'node.kubernetes.io/not-ready',
                                                 'operator': 'Exists',
                                                 'toleration_seconds': 300,
                                                 'value': None},
                                                {'effect': 'NoExecute',
                                                 'key': 'node.kubernetes.io/unreachable',
                                                 'operator': 'Exists',
                                                 'toleration_seconds': 300,
                                                 'value': None}],
                                'topology_spread_constraints': None,
                                'volumes': [{'aws_elastic_block_store': None,
                                             'azure_disk': None,
                                             'azure_file': None,
                                             'cephfs': None,
                                             'cinder': None,
                                             'config_map': {'default_mode': 420,
                                                            'items': [{'key': 'Corefile',
                                                                       'mode': None,
                                                                       'path': 'Corefile'}],
                                                            'name': 'coredns',
                                                            'optional': None},
                                             'csi': None,
                                             'downward_api': None,
                                             'empty_dir': None,
                                             'ephemeral': None,
                                             'fc': None,
                                             'flex_volume': None,
                                             'flocker': None,
                                             'gce_persistent_disk': None,
                                             'git_repo': None,
                                             'glusterfs': None,
                                             'host_path': None,
                                             'iscsi': None,
                                             'name': 'config-volume',
                                             'nfs': None,
                                             'persistent_volume_claim': None,
                                             'photon_persistent_disk': None,
                                             'portworx_volume': None,
                                             'projected': None,
                                             'quobyte': None,
                                             'rbd': None,
                                             'scale_io': None,
                                             'secret': None,
                                             'storageos': None,
                                             'vsphere_volume': None},
                                            {'aws_elastic_block_store': None,
                                             'azure_disk': None,
                                             'azure_file': None,
                                             'cephfs': None,
                                             'cinder': None,
                                             'config_map': None,
                                             'csi': None,
                                             'downward_api': None,
                                             'empty_dir': None,
                                             'ephemeral': None,
                                             'fc': None,
                                             'flex_volume': None,
                                             'flocker': None,
                                             'gce_persistent_disk': None,
                                             'git_repo': None,
                                             'glusterfs': None,
                                             'host_path': None,
                                             'iscsi': None,
                                             'name': 'kube-api-access-4dp5z',
                                             'nfs': None,
                                             'persistent_volume_claim': None,
                                             'photon_persistent_disk': None,
                                             'portworx_volume': None,
                                             'projected': {'default_mode': 420,
                                                           'sources': [{'config_map': None,
                                                                        'downward_api': None,
                                                                        'secret': None,
                                                                        'service_account_token': {'audience': None,
                                                                                                  'expiration_seconds': 3607,
                                                                                                  'path': 'token'}},
                                                                       {'config_map': {'items': [{'key': 'ca.crt',
                                                                                                  'mode': None,
                                                                                                  'path': 'ca.crt'}],
                                                                                       'name': 'kube-root-ca.crt',
                                                                                       'optional': None},
                                                                        'downward_api': None,
                                                                        'secret': None,
                                                                        'service_account_token': None},
                                                                       {'config_map': None,
                                                                        'downward_api': {'items': [
                                                                            {'field_ref': {'api_version': 'v1',
                                                                                           'field_path': 'metadata.namespace'},
                                                                             'mode': None,
                                                                             'path': 'namespace',
                                                                             'resource_field_ref': None}]},
                                                                        'secret': None,
                                                                        'service_account_token': None}]},
                                             'quobyte': None,
                                             'rbd': None,
                                             'scale_io': None,
                                             'secret': None,
                                             'storageos': None,
                                             'vsphere_volume': None}]}}]}


def kubernetes_logs_respnose():
    return "11:56:11.571 DEBUG: Using pattern 'cov/coverage.xml' to find reports " \
           "11:56:11.687 INFO: Python test coverage " \
           "11:56:11.689 INFO: Parsing report '/Users/lucasscheepers/Desktop/Lucas/School/Semester 8 - Stage IND/3. Implementation/ChatOps bot/cov/coverage.xml' " \
           "11:56:11.750 INFO: Sensor Cobertura Sensor for Python coverage [python] (done) | time=180ms"\
           "11:56:11.750 INFO: Sensor PythonXUnitSensor [python]"